package buildSrc

object Versions {

    const val material_design = "1.2.0-alpha05"
    const val firestore_ktx = "21.4.3"
    const val firebase_analytics = "17.4.0"
    const val firebase_auth = "19.3.1"
    const val firebase_database = "19.2.1"
    const val firebase_core_version = "17.4.0"
    const val firebase_messaging_version = "20.1.6"
    const val play_services_auth_version = "18.0.0"
    const val google_services_version = "4.3.3"
    const val androidx_version = "1.1.0"
    const val androidx_core_version = "1.2.0"
    const val androidx_lifecycle = "2.2.0"
    const val gradle_version = "3.5.1"
    const val kotlin_version = "1.3.61"
    const val retrofit_version = "2.7.0"
    const val okHttp_version = "3.11.0"
    const val coroutines_version = "1.3.3"
    const val room_version = "2.2.5"
    const val junit_version = "4.12"
    const val mockk_version = "1.9.3"
    const val dagger_version = "2.25.4"
    const val espresso_version = "3.2.0"
    const val junit_test_version = "1.1.1"
    const val gson_version = "2.8.6"
    const val navigation_version = "2.3.0-alpha02"
    const val lottie_version = "3.4.0"
    const val glide_version = "4.11.0"
    const val palette_version = "1.0.0"
    const val robolectric_version = "4.3.1"
    const val fragment_test_version = "1.2.2"
    const val threetenapb_version = "1.2.3"
    const val apachecommons_version = "3.10"

    // AndroidX
    const val androidx_appcompat_version = "1.0.2"
    const val androidx_cardview_version = "1.0.0"
    const val androidx_constraintlayout_version = "1.1.3"
    const val androidx_legacy_version = "1.0.0"
    const val androidx_multidex_version = "2.0.1"
    const val androidx_recyclerview_version = "1.1.0"
    const val androidx_transition_version = "1.0.0"
    const val androidx_core_testing = "2.1.0"
}
